language: node_js
node_js:
- '6'
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
env:
- EMBER_TRY_SCENARIO=ember-lts-2.4
- EMBER_TRY_SCENARIO=ember-lts-2.8
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm config set spin false
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add phantomjs-prebuilt
- phantomjs --version
install:
- yarn install --no-lockfile
script:
- node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: heroku
  api_key:
    secure: FN++IaJe7dda8yoE2djRoNWuHKyBBaiGVsx6q3bu0GTMQjzzbJAfp15tghl1+QAZemAvPCXxSDgQkIvqrFsYlwfvVB8kB16DRc9p5do5IOH+pQhQnGtNeUyKH0fQTjRfsBNfEW+eInguv9H8H6S+AVJiYO7tAFKZ/iSliM2TDP9jS2TOPS/vTls5qhqyVndS9RcMde6DHBjtUgXPnrDjBIlsrb35VFVX3rro4Dd/aIXxhqUtESfZUEqHwxT1Vix0vTKMUpbXeBTeIeH+l/eyQvPq1kkz8myIe4rJCPkc3xWc5LM1vO0l3XBz7bPkUAyaP+seKYkTEclurpUE/+g7CGG2bUrnnxi0Qsc8nbxu0uhJeUduEJu62QYU+j6aDVwHmbNc2Z1yKmYHqvk3vI6Weha8OVzcWmnBfU1HQKDVYkeIlyYnJIqMlCRESI0LS1n4n3mBi68q0SBGxFyU5SmVLcZTayAFH31OLq5sKNmGv6o5PJzZ7KKjs5tVsvpNBJfaaxH8NhlAftvCYqv0YRwEkQU6w3/jD5nsUBD/GCuc+6rA31AhR7a3IOGCn7A4AIa3xR3WryPcOLVWrmAaV2/VW0zHOBAHw5O+NK8go+OtY6u7s9n+KaXy3mmYA8GwxDFs6BJEeu3HFwev8yGuM6hoJF2rwGFkBZlmhUjqIhpHmAI=
  app: ember-parallax
  on:
    repo: mike-north/ember-parallax
